name: Deploy to Hostinger FTP

on:
  push:
    branches:
      - main  # Change to your deployment branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Deploy dist folder via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.edtech-community.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist
          server-dir: /home/u288920822/domains/edtech-community.com/public_html
          port: 21
